clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

when:
  branch: main
  event: push

steps:
  build:
    image: oven/bun:latest
    commands:
      - bun install
      - bun run build

  deploy:
    image: bitnami/git:latest
    commands:
      - cd course/.vitepress/dist
      - git init
      - git checkout -b pages
      - git add .
      - git config user.email "ci@woodpecker"
      - git config user.name "Woodpecker CI"
      - git commit -m "deploy"
      - git remote add origin https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git
      - git push -f origin pages
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
